services:
  server:
    build:
      context: .
      dockerfile: src/server/Dockerfile.server
    ports:
      - "7777:7777"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/organizer
      - NODE_ENV=development
      - PORT=7777
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
