services:
  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
      timeout: 5s

  server:
    build:
      context: .
      dockerfile: src/server/Dockerfile.server
    ports:
      - "7777:7777"
    environment:
      - MONGODB_URI=mongodb://mongo:MOZnxIqDzbEuLZkqFLsPZEyIQpDRUSRA@mongodb.railway.internal:27017
      - NODE_ENV=development
      - PORT=7777
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  mongo-data:
