services:
  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - MongoDB:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
      timeout: 5s

  server:
    build:
      context: .
      dockerfile: src/server/Dockerfile.server
    ports:
      - "7777:7777"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  MongoDB:
